language: elixir
elixir:
  - 1.7
  - 1.6
  - 1.5
  - 1.4
  - 1.3
  - 1.2
otp_release:
  - 21.0
  - 20.3
  - 19.3
  - 18.3
matrix:
  include:
  - elixir: 1.7
    otp_release: 21.0
    script:
      - MIX_ENV=cover mix coveralls.travis --trace
  exclude:
  - elixir: 1.7
    otp_release: 18.3
  - elixir: 1.6
    otp_release: 18.3
  - elixir: 1.5
    otp_release: 21.0
  - elixir: 1.4
    otp_release: 21.0
  - elixir: 1.3
    otp_release: 21.0
  - elixir: 1.3
    otp_release: 20.3
  - elixir: 1.2
    otp_release: 21.0
  - elixir: 1.2
    otp_release: 20.3
branches:
  only:
  - master
before_install:
  - mix local.rebar --force
script:
  - mix test --trace
